# Generated by Django 3.0.8 on 2020-07-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20200729_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
