# Generated by Django 3.0.7 on 2020-07-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0007_auto_20200702_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('format', models.CharField(choices=[('AN', 'alphanumeric'), ('NB', 'number'), ('AR', 'array')], max_length=2, verbose_name='format')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('domain_rules', models.CharField(max_length=120, verbose_name='domain rules')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameter',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=6, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ST', 'under study'), ('DV', 'under development'), ('HM', 'under test'), ('DP', 'deployed')], max_length=2),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Service')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
    ]
