# Generated by Django 3.0.8 on 2021-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_discountadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=1000)),
                ('userID', models.CharField(max_length=1000)),
                ('productID', models.CharField(max_length=1000)),
                ('dateTime', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='discountadvertisement',
            name='caption',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='discountadvertisement',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
