# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('lendmark', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField()),
                ('mobile_num', models.IntegerField()),
                ('tollfree_num', models.IntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('chief_officer', models.CharField(max_length=100)),
                ('establishment_act', models.CharField(max_length=300)),
                ('issue_date', models.DateField(max_length=20)),
                ('number_of_bades', models.IntegerField()),
                ('about_us', models.TextField()),
                ('logo', models.ImageField(upload_to='Images/logo/')),
                ('hospital_photo', models.ImageField(upload_to='Images/hospital_photo/')),
                ('reg_certificate', models.ImageField(upload_to='Images/reg_certificate/')),
                ('license_certificate', models.ImageField(upload_to='Images/license_certificate/')),
            ],
        ),
    ]
