# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0021_reportjob_finished_successfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='cibuild',
            name='changes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cibuild',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
