# Generated by Django 2.2.5 on 2019-10-05 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('attachment_url', models.CharField(max_length=255)),
                ('send_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GnGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_node', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('voice', models.FileField(null=True, upload_to='')),
                ('face', models.FileField(null=True, upload_to='')),
                ('salt', models.IntegerField()),
                ('pin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('voice', models.BooleanField(null=True)),
                ('face', models.BooleanField(null=True)),
                ('salt', models.IntegerField()),
                ('pin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('sns_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.User')),
            ],
        ),
        migrations.CreateModel(
            name='ChUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ScUser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ChGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroup', to='myapp_2.ScUser')),
            ],
        ),
        migrations.CreateModel(
            name='ChReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_date', models.DateTimeField()),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ChConversation')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ChMessage')),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ChGroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ScUser')),
            ],
        ),
        migrations.AddField(
            model_name='chmessage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ScUser'),
        ),
        migrations.AddField(
            model_name='chgroup',
            name='group_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.GnGroupType'),
        ),
        migrations.AddField(
            model_name='chgroup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.EsUser'),
        ),
        migrations.AddField(
            model_name='chconversation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_2.ScUser'),
        ),
    ]
